# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build a debug APK"
  lane :build do
    build_number = ENV['GITHUB_RUN_NUMBER'].to_i

    android_set_version_code(
      version_code: build_number,
      gradle_file: "./sampleapp/build.gradle"
    )

    gradle(
      task: "assemble",
      build_type: "Debug",
      print_command: true,
      properties: {
        "versionCode" => build_number,
      }
    )
  end
end
